import type { Playbook } from "@swarm/schema";
import { simulatedAdapter } from "./adapters.js";

const budget = {
  tokensLimit: 80_000,
  wallClockLimitMs: 180_000,
  maxLiveAgents: 16,
  maxConcurrentSubagents: 4,
  maxVisibleSubagents: 6,
  maxHandoffHops: 3,
  subagentTtlMs: 20_000,
} as const;

export const featureDevPlaybook: Playbook = {
  id: "feature-dev",
  name: "End-to-End Feature Development",
  trigger: "Build and test an authentication module.",
  layoutId: "feature-dev",
  qualityBar: "Password hashing, migrations, unit tests, and a security fuzz pass must land together.",
  constraints: [
    "Do not invent a new auth protocol",
    "Forward the original user prompt to every descendant",
    "Delivery cannot merge until backend and DB are both complete",
  ],
  budget,
  domains: [
    { id: "architecture", name: "Architecture", orchestratorId: "architecture" },
    { id: "delivery", name: "Delivery", orchestratorId: "delivery" },
  ],
  agents: [
    {
      id: "meta",
      name: "Meta-Orchestrator",
      kind: "meta",
      role: "Root dispatcher",
      stationId: "hq",
      hue: 48,
    },
    {
      id: "architecture",
      name: "Architecture",
      kind: "domain-orchestrator",
      domainId: "architecture",
      role: "Schema, libraries, review",
      stationId: "desk-arch",
      hue: 210,
    },
    {
      id: "delivery",
      name: "Delivery",
      kind: "domain-orchestrator",
      domainId: "delivery",
      role: "Pipelines, merge, errors",
      stationId: "desk-delivery",
      hue: 18,
    },
    {
      id: "backend",
      name: "Backend Agent",
      kind: "worker",
      domainId: "architecture",
      role: "Route handlers",
      stationId: "terminal-backend",
      hue: 145,
    },
    {
      id: "db",
      name: "DB Agent",
      kind: "worker",
      domainId: "architecture",
      role: "Migrations",
      stationId: "terminal-db",
      hue: 280,
    },
    {
      id: "qa",
      name: "QA Agent",
      kind: "worker",
      domainId: "delivery",
      role: "Test coordination",
      stationId: "terminal-qa",
      hue: 330,
    },
  ],
  tasks: [
    {
      id: "schema",
      title: "Break down auth schema",
      assignee: "architecture",
      domainId: "architecture",
      dependsOn: [],
      toolId: "design-schema",
      activity: "thinking",
      stationId: "desk-arch",
    },
    {
      id: "libs",
      title: "Select hashing libraries",
      assignee: "architecture",
      domainId: "architecture",
      dependsOn: ["schema"],
      toolId: "select-libs",
      activity: "thinking",
      stationId: "desk-arch",
    },
    {
      id: "routes",
      title: "Write route handlers and password hashing",
      assignee: "backend",
      domainId: "architecture",
      dependsOn: ["libs"],
      toolId: "write-routes",
      activity: "fetching",
      stationId: "terminal-backend",
    },
    {
      id: "migrations",
      title: "Generate migration scripts",
      assignee: "db",
      domainId: "architecture",
      dependsOn: ["libs"],
      toolId: "write-migrations",
      activity: "fetching",
      stationId: "terminal-db",
    },
    {
      id: "merge-code",
      title: "Validate and merge backend + DB outputs",
      assignee: "delivery",
      domainId: "delivery",
      dependsOn: ["routes", "migrations"],
      review: true,
      activity: "reviewing",
      stationId: "desk-delivery",
    },
    {
      id: "quality-pingpong",
      title: "Architecture quality review",
      assignee: "delivery",
      domainId: "delivery",
      dependsOn: ["merge-code"],
      activity: "reviewing",
      stationId: "desk-delivery",
      handoff: {
        to: "architecture",
        reason: "Quality threshold disagreement on hashing KDF parameters",
        duplicate: true,
      },
    },
    {
      id: "qa-suite",
      title: "Run auth test suite",
      assignee: "qa",
      domainId: "delivery",
      dependsOn: ["quality-pingpong"],
      toolId: "qa-plan",
      activity: "fetching",
      stationId: "terminal-qa",
      subagents: [
        {
          id: "unit",
          name: "Unit Test Runner",
          toolId: "unit-tests",
          stationId: "test-bay-1",
        },
        {
          id: "fuzzer",
          name: "Security Payload Fuzzer",
          toolId: "security-fuzzer",
          stationId: "test-bay-2",
        },
      ],
    },
  ],
  adapters: [
    simulatedAdapter("design-schema", 4200, 3200, {
      users: ["id", "email", "password_hash", "created_at"],
    }),
    simulatedAdapter("select-libs", 3800, 2800, { kdf: "argon2id", session: "jwt" }),
    simulatedAdapter("write-routes", 7200, 4500, {
      files: ["auth/routes.ts", "auth/hash.ts"],
    }),
    simulatedAdapter("write-migrations", 5100, 4200, {
      files: ["001_users.sql"],
    }),
    simulatedAdapter("qa-plan", 2200, 2500, { suites: ["unit", "fuzz"] }),
    simulatedAdapter("unit-tests", 3600, 3800, { passed: 24, failed: 0 }),
    simulatedAdapter("security-fuzzer", 4100, 4200, { findings: [] }),
  ],
};
