import type { Playbook } from "@swarm/schema";
import { simulatedAdapter } from "./adapters.js";

const budget = {
  tokensLimit: 90_000,
  wallClockLimitMs: 1_200_000,
  maxLiveAgents: 20,
  maxConcurrentSubagents: 4,
  maxVisibleSubagents: 6,
  maxHandoffHops: 3,
  subagentTtlMs: 16_000,
} as const;

export const marketIntelPlaybook: Playbook = {
  id: "market-intel",
  name: "Deep Market & Competitor Intelligence",
  trigger: "Produce an analysis of 5 direct competitors and their pricing changes.",
  layoutId: "market-intel",
  qualityBar: "Every competitor needs a current price, a currency, and a fact-check against archive data.",
  constraints: [
    "Standardize all prices to USD",
    "Flag conflicting facts instead of averaging them",
    "Keep the original five-competitor brief in every sub-agent envelope",
  ],
  budget,
  domains: [
    { id: "research", name: "Research", orchestratorId: "research" },
    { id: "synthesis", name: "Synthesis", orchestratorId: "synthesis" },
  ],
  agents: [
    {
      id: "meta",
      name: "Meta-Orchestrator",
      kind: "meta",
      role: "Root dispatcher",
      stationId: "hq",
      hue: 48,
    },
    {
      id: "research",
      name: "Research Director",
      kind: "domain-orchestrator",
      domainId: "research",
      role: "Assign targets, coverage gaps",
      stationId: "desk-research",
      hue: 195,
    },
    {
      id: "synthesis",
      name: "Synthesis Editor",
      kind: "domain-orchestrator",
      domainId: "synthesis",
      role: "Aggregate, standardize, flag conflicts",
      stationId: "desk-synthesis",
      hue: 32,
    },
    {
      id: "scraper-1",
      name: "Scraper A",
      kind: "worker",
      domainId: "research",
      role: "Landing pages",
      stationId: "terminal-web-1",
      hue: 125,
    },
    {
      id: "scraper-2",
      name: "Scraper B",
      kind: "worker",
      domainId: "research",
      role: "Pricing tables",
      stationId: "terminal-web-2",
      hue: 155,
    },
    {
      id: "scraper-3",
      name: "Scraper C",
      kind: "worker",
      domainId: "research",
      role: "Archive snapshots",
      stationId: "terminal-web-3",
      hue: 175,
    },
    {
      id: "factcheck",
      name: "Fact-Checker",
      kind: "worker",
      domainId: "synthesis",
      role: "Cross-reference archive",
      stationId: "terminal-facts",
      hue: 300,
    },
  ],
  tasks: [
    {
      id: "assign-targets",
      title: "Assign five competitor targets",
      assignee: "research",
      domainId: "research",
      dependsOn: [],
      toolId: "assign-targets",
      activity: "thinking",
      stationId: "desk-research",
    },
    {
      id: "scrape-a",
      title: "Scrape competitors 1–2",
      assignee: "scraper-1",
      domainId: "research",
      dependsOn: ["assign-targets"],
      toolId: "scrape-pages",
      toolInput: { targets: ["Northwind Cloud", "Contoso Mesh"] },
      activity: "fetching",
      stationId: "terminal-web-1",
      subagents: [
        { id: "parse-a1", name: "JSON parser", toolId: "parse-payload", stationId: "terminal-web-1" },
        { id: "parse-a2", name: "Price screenshot OCR", toolId: "parse-payload", stationId: "terminal-web-1" },
      ],
    },
    {
      id: "scrape-b",
      title: "Scrape competitors 3–4",
      assignee: "scraper-2",
      domainId: "research",
      dependsOn: ["assign-targets"],
      toolId: "scrape-pages",
      toolInput: { targets: ["Globex Edge", "Initech Flow"] },
      activity: "fetching",
      stationId: "terminal-web-2",
      subagents: [
        { id: "parse-b1", name: "JSON parser", toolId: "parse-payload", stationId: "terminal-web-2" },
      ],
    },
    {
      id: "scrape-c",
      title: "Scrape competitor 5 + archive",
      assignee: "scraper-3",
      domainId: "research",
      dependsOn: ["assign-targets"],
      toolId: "scrape-pages",
      toolInput: { targets: ["Umbrella API"] },
      activity: "fetching",
      stationId: "terminal-web-3",
      subagents: [
        { id: "parse-c1", name: "Archive parser", toolId: "parse-payload", stationId: "terminal-web-3" },
      ],
    },
    {
      id: "coverage",
      title: "Track coverage gaps",
      assignee: "research",
      domainId: "research",
      dependsOn: ["scrape-a", "scrape-b", "scrape-c"],
      review: true,
      activity: "reviewing",
      stationId: "desk-research",
    },
    {
      id: "aggregate",
      title: "Aggregate findings and standardize currency",
      assignee: "synthesis",
      domainId: "synthesis",
      dependsOn: ["coverage"],
      toolId: "aggregate",
      review: true,
      activity: "reviewing",
      stationId: "desk-synthesis",
    },
    {
      id: "facts",
      title: "Cross-reference pricing with archive",
      assignee: "factcheck",
      domainId: "synthesis",
      dependsOn: ["aggregate"],
      toolId: "fact-check",
      activity: "fetching",
      stationId: "terminal-facts",
    },
    {
      id: "conflicts",
      title: "Flag conflicting facts",
      assignee: "synthesis",
      domainId: "synthesis",
      dependsOn: ["facts"],
      toolId: "flag-conflicts",
      activity: "thinking",
      stationId: "desk-synthesis",
    },
  ],
  adapters: [
    simulatedAdapter("assign-targets", 3100, 2400, {
      competitors: ["Northwind Cloud", "Contoso Mesh", "Globex Edge", "Initech Flow", "Umbrella API"],
    }),
    simulatedAdapter("scrape-pages", 5400, 4200, (input: unknown) => ({
      pages: input,
      captured: true,
    })),
    simulatedAdapter("parse-payload", 1800, 1600, { rows: 12, currency: "mixed" }),
    simulatedAdapter("aggregate", 4800, 3600, {
      usd: true,
      rows: 5,
    }),
    simulatedAdapter("fact-check", 3900, 3400, {
      matched: 4,
      conflicts: 1,
    }),
    simulatedAdapter("flag-conflicts", 2600, 2200, {
      flags: ["Globex Edge list vs archive delta +18%"],
    }),
  ],
};
